# JSON to MySQL and Pandas Data Manipulation

This notebook implements the given assignment using JSON, MySQL and Pandas.

## 1. Import Required Libraries

In [2]:
%pip install pandas==2.3.3 mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas==2.3.3
  Using cached pandas-2.3.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: mysql-connector-python in C:\Users\darsh\AppData\Roaming\Python\Python314\site-packages (26.7.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\darsh\AppData\Roaming\Python\Python314\site-packages (from pandas==2.3.3) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\darsh\AppData\Roaming\Python\Python314\site-packages (from pandas==2.3.3) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas==2.3.3)
  Using cached pytz-2026.4-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\darsh\AppData\Roaming\Python\Python314\site-packages (from pandas==2.3.3) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\darsh\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas==2.3.3) (1.17.0)
Using cached pandas-2.3.3-cp314-cp314-win_amd64.whl (11.1 MB)
Using cached pytz-2026.4-py2.py3-none-any.whl (506 kB)
Installing collected packages: pytz, pandas

   ---------------------------------------- 0/2 [pytz]
   ---------------------------------------- 0/2 [pytz]
   ---------------------------------------- 0/2 [pytz]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-2.3.3 pytz-2026.4
Note: you may need to restart the kernel to use updated packages.

In [3]:
import json
import pandas as pd
import mysql.connector

## 2. Load JSON Data

In [4]:
with open("sample_data_for_assignment.json", "r") as file:
    json_data = json.load(file)

print(json_data.keys())

dict_keys(['cols', 'data'])

## 3. View JSON Columns and Data

In [5]:
print("Columns:", json_data["cols"])
print("Number of rows:", len(json_data["data"]))

Columns: ['id', 'name', 'email', 'postalZip', 'phone']
Number of rows: 10

## 4. Connect to MySQL

In [6]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="amr123"
)

cursor = connection.cursor()
print("Connected to MySQL")

Connected to MySQL

## 5. Create Database

In [7]:
cursor.execute("CREATE DATABASE IF NOT EXISTS json_assignment")
cursor.execute("USE json_assignment")
print("Database selected")

Database selected

## 6. Create MySQL Table

In [8]:
create_table_query = """
CREATE TABLE IF NOT EXISTS Users (
    id INT,
    name VARCHAR(100),
    email VARCHAR(150),
    postalZip VARCHAR(50),
    phone VARCHAR(50)
)
"""

cursor.execute(create_table_query)
print("Table created")

Table created

## 7. Load JSON Data into MySQL

In [9]:
insert_query = """
INSERT INTO Users
(id, name, email, postalZip, phone)
VALUES (%s, %s, %s, %s, %s)
"""

cursor.execute("TRUNCATE TABLE Users")
cursor.executemany(insert_query, json_data["data"])
connection.commit()

print("Data loaded into MySQL")

Data loaded into MySQL

## 8. Read Data from MySQL

In [10]:
cursor.execute("SELECT * FROM Users")
rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Alice Johnson', 'alice.johnson@outlook.com', '560001', '(816) 530-4269')
(2, 'Bob Smith', 'bob.smith@yahoo.com', '560002', '1-811-920-9732')
(3, 'Carol Williams', 'carol.williams@example.org', 'KA560003', '9876543210')
(4, 'David Brown', 'david.brown@company.in', '560004', '(080) 123-4567')
(5, 'Emma Davis', 'emma.davis@protonmail.com', 'ZIP560005', '65-30-42-69')
(6, 'Frank Miller', 'frank.miller@hotmail.com', '560006', '1234567890')
(7, 'Grace Wilson', 'grace.wilson@mail.com', '560007A', '9988776655')
(8, 'Henry Moore', 'henry.moore@domain.net', '560008', '91-65-09-73-2')
(9, 'Ivy Taylor', 'ivy.taylor@gmail.com', 'BLR560009', '(65) 11-92-73')
(10, 'Jack Anderson', 'jack.anderson@icloud.com', '560010', '70 80 90 12')

## 9. Load MySQL Data into Pandas DataFrame

The data is read from MySQL and stored in a Pandas DataFrame.

In [11]:
cursor.execute("SELECT * FROM Users")
rows = cursor.fetchall()
columns = [column[0] for column in cursor.description]

df = pd.DataFrame(rows, columns=columns)
df

   id            name                       email  postalZip           phone
0   1   Alice Johnson   alice.johnson@outlook.com     560001  (816) 530-4269
1   2       Bob Smith         bob.smith@yahoo.com     560002  1-811-920-9732
2   3  Carol Williams  carol.williams@example.org   KA560003      9876543210
3   4     David Brown      david.brown@company.in     560004  (080) 123-4567
4   5      Emma Davis   emma.davis@protonmail.com  ZIP560005     65-30-42-69
5   6    Frank Miller    frank.miller@hotmail.com     560006      1234567890
6   7    Grace Wilson       grace.wilson@mail.com    560007A      9988776655
7   8     Henry Moore      henry.moore@domain.net     560008   91-65-09-73-2
8   9      Ivy Taylor        ivy.taylor@gmail.com  BLR560009   (65) 11-92-73
9  10   Jack Anderson    jack.anderson@icloud.com     560010     70 80 90 12

## 10. Display All Data

In [12]:
display(df)

   id            name                       email  postalZip           phone
0   1   Alice Johnson   alice.johnson@outlook.com     560001  (816) 530-4269
1   2       Bob Smith         bob.smith@yahoo.com     560002  1-811-920-9732
2   3  Carol Williams  carol.williams@example.org   KA560003      9876543210
3   4     David Brown      david.brown@company.in     560004  (080) 123-4567
4   5      Emma Davis   emma.davis@protonmail.com  ZIP560005     65-30-42-69
5   6    Frank Miller    frank.miller@hotmail.com     560006      1234567890
6   7    Grace Wilson       grace.wilson@mail.com    560007A      9988776655
7   8     Henry Moore      henry.moore@domain.net     560008   91-65-09-73-2
8   9      Ivy Taylor        ivy.taylor@gmail.com  BLR560009   (65) 11-92-73
9  10   Jack Anderson    jack.anderson@icloud.com     560010     70 80 90 12

## 11. Change Email Addresses

Change the domain of every email address to `gmail.com`.

In [13]:
df["email"] = df["email"].str.replace(r"@.*", "@gmail.com", regex=True)
df[["email"]]

                      email
0   alice.johnson@gmail.com
1       bob.smith@gmail.com
2  carol.williams@gmail.com
3     david.brown@gmail.com
4      emma.davis@gmail.com
5    frank.miller@gmail.com
6    grace.wilson@gmail.com
7     henry.moore@gmail.com
8      ivy.taylor@gmail.com
9   jack.anderson@gmail.com

## 12. Convert postalZip to Integer

Remove letters and other non-numeric characters, then convert the values to integers.

In [14]:
df["postalZip"] = (
    df["postalZip"]
    .astype(str)
    .str.replace(r"\D", "", regex=True)
    .astype(int)
)

df[["postalZip"]]

   postalZip
0     560001
1     560002
2     560003
3     560004
4     560005
5     560006
6     560007
7     560008
8     560009
9     560010

## 13. Phone Number Conversion Function

Remove formatting, take two digits at a time, and convert them to ASCII. Values below 65 are replaced with `O`.

In [15]:
def phone_to_ascii(phone):
    digits = ''.join(char for char in str(phone) if char.isdigit())
    result = ''

    for i in range(0, len(digits) - 1, 2):
        number = int(digits[i:i + 2])

        if number < 65:
            result += 'O'
        else:
            result += chr(number)

    return result

## 14. Test the Phone Function

In [16]:
print(phone_to_ascii("(816) 530-4269"))
print(phone_to_ascii("1-811-920-9732"))

QAOOE
OO\OI

## 15. Apply Phone Conversion to the DataFrame

In [17]:
df["phone"] = df["phone"].apply(phone_to_ascii)
df[["phone"]]

   phone
0  QAOOE
1  OO\OI
2  bLOOO
3  OOOOC
4   AOOE
5  OOONZ
6  cXMBO
7   [AOI
8   AO\I
9   FPZO

## 16. Final DataFrame

In [18]:
display(df)

   id            name                     email  postalZip  phone
0   1   Alice Johnson   alice.johnson@gmail.com     560001  QAOOE
1   2       Bob Smith       bob.smith@gmail.com     560002  OO\OI
2   3  Carol Williams  carol.williams@gmail.com     560003  bLOOO
3   4     David Brown     david.brown@gmail.com     560004  OOOOC
4   5      Emma Davis      emma.davis@gmail.com     560005   AOOE
5   6    Frank Miller    frank.miller@gmail.com     560006  OOONZ
6   7    Grace Wilson    grace.wilson@gmail.com     560007  cXMBO
7   8     Henry Moore     henry.moore@gmail.com     560008   [AOI
8   9      Ivy Taylor      ivy.taylor@gmail.com     560009   AO\I
9  10   Jack Anderson   jack.anderson@gmail.com     560010   FPZO

## 17. Close MySQL Connection

In [19]:
cursor.close()
connection.close()
print("MySQL connection closed")

MySQL connection closed